[package]
name = "must"
version = "0.1.0"
authors = ["Braxton Schafer <braxton@epic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = '0.24.1'
libc = '0.2.71'
clap = "3.0.0"
spinners = "1.2.0"
tar = "0.4"
